[package]
name = "badvestments"
version = "0.1.0"
authors = ["David Keeler <mozkeeler@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
lalrpop-util = "0.13.1"
regex = "0.2.1"
rand = "0.3.15"
twitter-api = "0.3.0"
oauth-client = "0.3.2"
